version: "3"

services:
  mongo:
    image: mongo:6
    hostname: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
  bot:
    build:
      context: survey_bot
      dockerfile: Dockerfile
    hostname: bot
    command: python -m survey_bot
    env_file:
      - .env
    volumes:
      - ./survey_bot:/app/survey_bot
    depends_on:
      - mongo
  web:
    build:
      context: survey_web
      dockerfile: Dockerfile
    hostname: web
    env_file:
      - .env
    volumes:
      - ./survey_web:/app/survey_web
    ports:
      - "3000:3000"
    depends_on:
      - mongo
volumes:
  mongodata: